config/routes.rb
Rails.application.routes.draw do

  # devise_for :users, controllers: {
  # 	sessions: 'users/sessions',
  # 	registrations: 'users/registrations'
  # }

  devise_for :users
  root 'books#top'
  post 'books/:id' => 'books#create'
  get 'home/about' => 'books#top'

  resources :books
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :books, dependent: :destroy
   attachment :profile_image
   	validates :name, presence: true, uniqueness: true,
					 length: { minimum: 2, maximum: 20 }
	validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :authenticate_user!, except: [:top]
	 before_action :configure_permitted_parameters, if: :devise_controller?

	 def after_sign_in_path_for(resorce)
	 	user_path(resorce)
	 end

	 def after_sign_out_path_for(resource)
	 	root_path(resource)
	 end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def about
  end

  def index
  	@book = Book.new
  	@books = Book.all
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
  	  redirect_to book_path(@book.id), notice: 'Book was successfully created'

    else
      @books = Book.all
      render action: :index
    end
  end

  def edit
     @book = Book.find(params[:id])
  if current_user.id != @book.user_id
     redirect_to books_path
  end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id), notice: 'Book was successfully updated'
    else
      flash.now[:notice] = 'update error'
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
  	 params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only:[:edit, :update]

  def index
    @user = current_user
  	@users = User.all
    @book = Book.new
  end

  def show
  	 @user = User.find(params[:id])
     @book = Book.new
     @books = Book.where(user_id:params[:id])
  end

  def edit
  end

  def update
    @user.update(user_params)
  if @user.save
     redirect_to user_path(@user.id), notice: 'You have updated user successfully'
  else
    flash.now[:notice] = 'update error'
    render action: :edit
  end
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
  if current_user.id != @user.id
    redirect_to user_path(current_user)
  end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/about.html.erb
<h1 class="about">Welcom to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<p id="notice"><%= notice %></p>

<%= form_for(@book) do |f| %>

    <div class="form-group has-icon">
        <label class="control-label sr-only" for="inputEmail">Title</label>
        <h4>Title</h4>
        <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"タイトルを入力してください"%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

    <div class="form-group has-icon">
        <label class="control-label sr-only" for="inputEmail">Opinion</label>
        <h4>Opinion</h4>
        <%= f.text_field :body, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"本文を入力してください"%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

        <%= f.submit "Update Book", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
    <%= link_to "Show", book_path %>
    <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'layouts/template', user: current_user, book: @book %>

		<div class="col-xs-9">
			<table class="table table-striped">
				<h1>Books</h1>
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to (book.user) do %>
									<%= attachment_image_tag book.user, :profile_image, size:"60x60", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "noimage.jpg" %>
								<% end %>
							</td>
							<td>
								<%= link_to book_path(book.id) do %>
									<%= book.title %>
								<% end %>
							</td>
							<td>
								<%= book.body %>
							</td>
						</tr>
						<td>
						</td>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= form_for(@book, url: post_book_path) do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<%= render 'layouts/template', user: current_user, book: Book.new %>

		<div class="col-xs-9">
			<table class="table table-striped">
				<h1>Book detail</h1>
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>

					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag @book.user, :profile_image, size:"60x60", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "noimage.jpg" %>
							<% end %>
						</td>
						<td>
							<%= @book.title %>
						</td>
						<td>
							<%= @book.body %>
						</td>
						<td>
							<% if @book.user.id == current_user.id %>
							<%= link_to "Edit",edit_book_path(@book.id) %>
						</td>
						<td>
							<%= link_to "Destroy",book_path(@book.id), method: :delete, data: {confirm: "Are you sure?"} %>
							<% end %>
						</td>
					</tr>
						<td>
							<%= link_to user_path(@book.user) do %>
							<%= @book.user.name %>
							<% end %>
						</td>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/top.html.erb
<div class="top-page">
	<div class="top-page-content">
		<h1 class="top">
		<span style="color: black" class="glyphicon glyphicon-book" aria-hidden="true">
	 	</span>welcome to Bookers!!
		</h1>

		<p>
		In<span style="color: black" class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers
		</p>

		<p>
		you can share and exchange your opinions , inpressions , and emotions

		about various books!
		</p>

	<p class="log-in-button">
	<%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-block' %>
	</p>
	<p class="sign-up-button">
	<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-block' %>
	</p>
	</div>

	<p class="footer">
		CopyRight Infratop.inc
	</p>
</div>

app/views/layouts/_template.html.erb
		<div class="col-xs-3">
	　		<h1>User info</h1>
			<%= attachment_image_tag user, :profile_image, size:"60x60", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "noimage.jpg" %>
	    <h3 class="profile-name">name
	    	<div class="user-name">
	    		<%= user.name %>
	    	</div>
	    </h3>

	    <h3 class="profile-introduction">introduction
	    	<div class="user-introduction">
				<%= user.introduction %>
			</div>
	    </h3>
	    	<% if user == current_user %>

		    	<%= link_to edit_user_path(current_user), class: 'btn btn-default' do %>
		    	<span style="color: black" class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
		    	<% end %>
		    <% else %>
		    	<%= link_to user_path(current_user), class: 'btn btn-default' do %>
		    	<span style="color: black" class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
		    	<% end %>
		    <% end %>

			<h3>New book</h3>

			<div class="form">
				<%= form_for(book) do |f| %>
					<% if book.errors.any? %>
		 				<% book.errors.full_messages.each do |message| %>
		        	<li><%= message %></li>
		    　　	<% end %>
						error
					<% end %>

					<h4>Title</h4>
					<%= f.text_field :title %>

					<h4>Opinion</h4>
					<%= f.text_area :body %>

					<div class="form-button">
						<%= f.submit 'Create Book' %>
					</div>
				<% end %>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
<header class="navbar navbar-fixed-top navbar-inverse">
    <!-- <nav class="navbar navbar-dark bg-dark"> -->
     <div class="container-fluid">
      <div class="navbar-header">
      <h4>Bookers</h4>

  </div>

  <div class="collapse navbar-collapse" id="navbarTop">
      <ul class="nav navbar-right">
<% if user_signed_in? %>
  <span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to 'Home', user_path(current_user.id) %>

  <span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= link_to "Users", users_path %>

  <span class="glyphicon glyphicon-book" aria-hidden="true"></span><%= link_to "Books", books_path %>

  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span><%= link_to "logout", destroy_user_session_path, method: :delete %>
<% else %>

  <span class="glyphicon glyphicon-home" aria-hidden="true"></span><%= link_to "Home", root_path %>

  <span class="glyphicon glyphicon-link" aria-hidden="true"></span><%= link_to "About", '/home/about' %>

  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><%= link_to "sign up", new_user_registration_path %>

  <span class="glyphicon glyphicon-share" aria-hidden="true"></span><%= link_to "login", new_user_session_path %>

<% end %>
</ul>
</div>
</nav>
</header>
<%= yield %>
    </body>
</html>

app/views/users/edit.html.erb
<h1>User info</h1>
<p id="notice"><%= notice %></p>

<%= form_for(@user) do |f| %>
    <h4>Name</h4>
    <%= f.text_field :name %>
    <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
    <h4>Image</h4>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    <h4>Introduction</h4>
    <%= f.text_area :introduction %>
    <%= f.submit 'Update User' %>
<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<%= render 'layouts/template', user: current_user, book: @book %>

		<div class="col-xs-9">
			<table class="table table-striped">
				<h1>Users</h1>
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td>
								<%= attachment_image_tag user, :profile_image, size:"60x60", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "noimage.jpg" %>
							</td>
							<td>
							<%= user.name %>
							</td>
							<td>
							<%= link_to 'Show', user_path(user.id) %>
							</td>
						</tr>
							<td>
							</td>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
  		<%= render 'layouts/template', user: @user, book: @book %>

  		<div class="col-xs-9">
   			<table class="table table-striped">
    			<h1>Books</h1>
   				<thead>
   					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td>
								<%= attachment_image_tag @user, :profile_image, size:"60x60", format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "noimage.jpg" %>
							</td>
							<td>
								<%= link_to book_path(book.id) do %>
									<%= book.title %>
								<% end %>
							</td>
							<td>
								<%= book.body %>
							</td>
						</tr>
							<td>
							</td>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>